// Generated by CoffeeScript 1.7.1
(function() {
  var MovieID, iterate, listMovie, loadMovie, randomID, swipe, yesList;

  randomID = '';

  yesList = [];

  MovieID = '';

  $(function() {
    var r;
    r = Math.floor(Math.random() * 100000);
    randomID = '' + r;
    iterate();
    return loadMovie(MovieID);
  });

  $('.yes').click(function(event) {
    yesList[yesList.length] = MovieID;
    iterate();
    return loadMovie(MovieID);
  });

  $('.no').click(function(event) {
    iterate();
    return loadMovie(MovieID);
  });

  $('.quit').click(function(event) {
    return listMovie(yesList);
  });

  iterate = function() {
    var i;
    i = parseInt(randomID);
    i = i + 1;
    randomID = '' + i;
    if (randomID.length < 7) {
      while (randomID.length < 7) {
        randomID = '0' + randomID;
      }
    }
    return MovieID = 'tt' + randomID;
  };

  listMovie = function(array) {
    var i, resp, _i, _ref, _results;
    $('body').html("<h1>List of movies to watch</h1>");
    _results = [];
    for (i = _i = 0, _ref = array.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      resp = $.ajax("http://www.omdbapi.com/?i=" + array[i], {
        type: 'GET',
        dataType: "json"
      });
      _results.push(resp.done(function(movie) {
        return $('body').append("<p>" + movie.Title + "</p>");
      }));
    }
    return _results;
  };

  loadMovie = function(movieID) {
    var resp;
    resp = $.ajax("http://www.omdbapi.com/?i=" + movieID, {
      type: 'GET',
      dataType: "json"
    });
    return resp.done(function(movie) {
      if (movie.Poster === 'N/A') {
        $('.poster').html("<img src=noimage.jpg>");
      } else {
        $('.poster').html("<img src='" + movie.Poster + "'>");
      }
      $('.actors').html("" + movie.Actors);
      $('.name > h1').html("" + movie.Title);
      return $('.plot').html("" + movie.Plot);
    });
  };

  swipe = function() {};

}).call(this);

//# sourceMappingURL=main.map
